"""
Backward-compatibility shim.
All scraping logic has been modularized into the `scrapers/` package.
"""
from __future__ import annotations

from scrapers import (
    Job,
    BaseScraper,
    USER_AGENTS,
    NON_JOB_DOMAINS,
    PRE_FILTER_DISQUALIFIERS,
    NOISE_COMPANY_PATTERNS,
    COMPANY_STRIP_SUFFIXES,
    get_random_headers,
    get_session,
    is_valid_job_offer,
    clean_job_description,
    clean_company_name,
    normalize_company_name,
    normalize_title_name,
    get_job_dedup_key,
    normalize_title_company_for_hash,
    LinkedInScraper,
    ITJobsScraper,
    IndeedScraper,
    LandingJobsScraper,
    RemotiveScraper,
    ArbeitnowScraper,
    RemoteOKScraper,
    CargaDeTrabalhosScraper,
    JobicyScraper,
    NetEmpregosScraper,
    JobspressoScraper,
    EuraxessScraper,
    IEFPScraper,
    JobIngestionPipeline,
)

__all__ = [
    "Job",
    "BaseScraper",
    "USER_AGENTS",
    "NON_JOB_DOMAINS",
    "PRE_FILTER_DISQUALIFIERS",
    "NOISE_COMPANY_PATTERNS",
    "COMPANY_STRIP_SUFFIXES",
    "get_random_headers",
    "get_session",
    "is_valid_job_offer",
    "clean_job_description",
    "clean_company_name",
    "normalize_company_name",
    "normalize_title_name",
    "get_job_dedup_key",
    "normalize_title_company_for_hash",
    "LinkedInScraper",
    "ITJobsScraper",
    "IndeedScraper",
    "LandingJobsScraper",
    "RemotiveScraper",
    "ArbeitnowScraper",
    "RemoteOKScraper",
    "CargaDeTrabalhosScraper",
    "JobicyScraper",
    "NetEmpregosScraper",
    "JobspressoScraper",
    "EuraxessScraper",
    "IEFPScraper",
    "JobIngestionPipeline",
]
