[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#070A11"
secondaryBackgroundColor = "#0C1220"
textColor = "#F1F5F9"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = true

[server]
runOnSave = true
fileWatcherType = "auto"
